# fly.toml app configuration file generated for noitamap on 2023-12-27T07:09:42+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "noitamap"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
